name: Finance
modelClass: NielsVanDenDries\Toolkit\Models\Finance
form: $/NielsVanDenDries/toolkit/models/finance/fields.yaml
defaultRedirect: NielsVanDenDries/toolkit/finance
create:
    redirect: 'NielsVanDenDries/toolkit/finance/update/:id'
    redirectClose: NielsVanDenDries/toolkit/finance
update:
    redirect: NielsVanDenDries/toolkit/finance
    redirectClose: NielsVanDenDries/toolkit/finance
preview: {  }
