# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Sale

# Model Form Field configuration
form: $/nielsvandendries/toolkit/models/sale/fields.yaml

# Model Class name
modelClass: Nielsvandendries\Toolkit\Models\Sale

# Default redirect location
defaultRedirect: nielsvandendries/toolkit/sales

# Create page
create:
    title: backend::lang.form.create_title
    redirect: nielsvandendries/toolkit/sales/update/:id
    redirectClose: nielsvandendries/toolkit/sales

# Update page
update:
    title: backend::lang.form.update_title
    redirect: nielsvandendries/toolkit/sales
    redirectClose: nielsvandendries/toolkit/sales

# Preview page
preview:
    title: backend::lang.form.preview_title
