name: FileManager
modelClass: NielsVanDenDries\Toolkit\Models\FileManager
form: $/NielsVanDenDries/toolkit/models/filemanager/fields.yaml
defaultRedirect: NielsVanDenDries/toolkit/filemanager
create:
    redirect: 'NielsVanDenDries/toolkit/filemanager/update/:id'
    redirectClose: NielsVanDenDries/toolkit/filemanager
update:
    redirect: NielsVanDenDries/toolkit/filemanager
    redirectClose: NielsVanDenDries/toolkit/filemanager
preview: {  }
