title: FileManager
modelClass: NielsVanDenDries\Toolkit\Models\FileManager
list: $/NielsVanDenDries/toolkit/models/filemanager/columns.yaml
recordUrl: 'NielsVanDenDries/toolkit/filemanager/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
